import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Clear existing data to avoid duplicates
  // await prisma.userFavorites.deleteMany({})
  // await prisma.recipeTag.deleteMany({})
  // await prisma.ingredient.deleteMany({})
  // await prisma.recipe.deleteMany({})
  // await prisma.tag.deleteMany({})
  // await prisma.user.deleteMany({})

  // Create a user (the owner of the recipes)
  const user = await prisma.user.create({
    data: {
      email: 'chef@byte-chefs.com',
      firstName: 'Gordon',
      lastName: 'Ramsay',
      aboutMe: 'Passionate about authentic, high-quality recipes.',
      profileImage:
        'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      allergens: [],
      role: 'admin',
    },
  })

  // Create Tags
  const tags = await createTags()

  // Create recipes
  await createRecipes(user.id, tags)

  console.log('Seeding finished.')
}

async function createTags() {
  const tagData = [
    { name: 'Italian', include: ['pasta', 'pizza', 'risotto'], exclude: [] },
    { name: 'Healthy', include: ['salad', 'low calorie'], exclude: ['fried'] },
    { name: 'Mexican', include: ['tacos', 'salsa', 'guacamole'], exclude: [] },
    { name: 'Asian', include: ['stir-fry', 'noodles', 'rice'], exclude: [] },
    { name: 'Indian', include: ['curry', 'spicy', 'masala'], exclude: [] },
    { name: 'Mediterranean', include: ['olive oil', 'feta', 'hummus'], exclude: [] },
    { name: 'Dessert', include: ['sweet', 'cake', 'chocolate'], exclude: ['savory'] },
    { name: 'Breakfast', include: ['eggs', 'toast', 'pancakes'], exclude: [] },
    { name: 'Vegetarian', include: ['vegetables', 'plant-based'], exclude: ['meat'] },
    { name: 'Vegan', include: ['plant-based'], exclude: ['meat', 'dairy', 'eggs'] },
    { name: 'Gluten-Free', include: ['rice', 'corn'], exclude: ['wheat', 'gluten'] },
    { name: 'Quick Meals', include: ['fast', 'easy'], exclude: ['complex'] },
    { name: 'Seafood', include: ['fish', 'shrimp', 'seafood'], exclude: [] },
    { name: 'Baking', include: ['bread', 'pastry', 'baked'], exclude: [] },
    { name: 'Grilling', include: ['bbq', 'grilled'], exclude: [] },
    { name: 'French', include: ['french', 'pastry', 'cream'], exclude: [] },
    { name: 'Middle Eastern', include: ['hummus', 'tahini', 'pita'], exclude: [] },
    { name: 'Greek', include: ['feta', 'olive', 'yogurt'], exclude: [] },
    { name: 'Spanish', include: ['paella', 'tapas', 'chorizo'], exclude: [] },
    { name: 'American', include: ['burger', 'bbq', 'sandwich'], exclude: [] },
    { name: 'Hard', include: ['complex', 'difficult'], exclude: ['easy'] }, // Added missing tag
  ]

  const createdTags = {}

  for (const tag of tagData) {
    const createdTag = await prisma.tag.create({
      data: {
        name: tag.name,
        include: tag.include,
        exclude: tag.exclude,
      },
    })
    createdTags[tag.name] = createdTag
  }

  return createdTags
}

async function createRecipes(userId, tags) {
  const recipes = [
    // Original recipes
    {
      name: 'Spaghetti Carbonara',
      photo:
        'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 30,
      description: [
        'Step 1: Bring a large pot of salted water to a boil.',
        'Step 2: Add spaghetti and cook until al dente.',
        'Step 3: Meanwhile, fry pancetta in a pan until crisp.',
        'Step 4: Whisk eggs with grated Parmesan cheese in a bowl.',
        'Step 5: Drain pasta and reserve some cooking water.',
        'Step 6: Quickly mix pasta with pancetta and remove from heat.',
        'Step 7: Stir in the egg and cheese mixture, adding reserved water if needed to form a creamy sauce.',
        'Step 8: Season with freshly ground black pepper and serve immediately.',
      ],
      calories: 600,
      carbs: 45,
      fat: 30,
      protein: 25,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 2,
      ingredients: [
        { foodId: 1, servingId: 1, quantity: 200, name: 'Spaghetti' },
        { foodId: 2, servingId: 1, quantity: 100, name: 'Pancetta' },
        { foodId: 3, servingId: 1, quantity: 2, name: 'Eggs' },
        { foodId: 4, servingId: 1, quantity: 50, name: 'Parmesan Cheese' },
      ],
      tagNames: ['Italian'],
    },
    // Italian Recipes
    {
      name: 'Margherita Pizza',
      photo:
        'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 45,
      description: [
        'Step 1: Prepare pizza dough and let it rise.',
        'Step 2: Roll out the dough into a circle.',
        'Step 3: Spread tomato sauce over the dough.',
        'Step 4: Add slices of fresh mozzarella.',
        'Step 5: Bake in a preheated oven at 475°F for 10-12 minutes.',
        'Step 6: Top with fresh basil leaves and drizzle with olive oil.',
      ],
      calories: 850,
      carbs: 90,
      fat: 35,
      protein: 30,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 10, servingId: 1, quantity: 1, name: 'Pizza Dough' },
        { foodId: 11, servingId: 1, quantity: 200, name: 'Tomato Sauce' },
        { foodId: 12, servingId: 1, quantity: 200, name: 'Fresh Mozzarella' },
        { foodId: 13, servingId: 1, quantity: 10, name: 'Fresh Basil Leaves' },
        { foodId: 14, servingId: 1, quantity: 2, name: 'Olive Oil' },
      ],
      tagNames: ['Italian', 'Vegetarian'],
    },
    {
      name: 'Lasagna',
      photo:
        'https://images.pexels.com/photos/6046493/pexels-photo-6046493.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 90,
      description: [
        'Step 1: Prepare meat sauce with ground beef, onions, garlic, and tomatoes.',
        'Step 2: Make béchamel sauce with butter, flour, and milk.',
        'Step 3: Cook lasagna noodles until al dente.',
        'Step 4: Layer noodles, meat sauce, béchamel, and cheese in a baking dish.',
        'Step 5: Repeat layers until all ingredients are used.',
        'Step 6: Top with mozzarella and Parmesan cheese.',
        'Step 7: Bake at 375°F for 30-35 minutes until bubbly and golden.',
      ],
      calories: 750,
      carbs: 55,
      fat: 40,
      protein: 35,
      favouritesTotal: 0,
      difficulty: 'hard',
      status: 'published',
      personServing: 8,
      ingredients: [
        { foodId: 22, servingId: 1, quantity: 500, name: 'Ground Beef' },
        { foodId: 23, servingId: 1, quantity: 500, name: 'Tomato Sauce' },
        { foodId: 24, servingId: 1, quantity: 250, name: 'Lasagna Noodles' },
        { foodId: 25, servingId: 1, quantity: 200, name: 'Mozzarella Cheese' },
        { foodId: 26, servingId: 1, quantity: 50, name: 'Parmesan Cheese' },
        { foodId: 27, servingId: 1, quantity: 500, name: 'Béchamel Sauce' },
      ],
      tagNames: ['Italian'],
    },
    // Mexican Recipes
    {
      name: 'Beef Tacos',
      photo:
        'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 30,
      description: [
        'Step 1: Season ground beef with taco seasoning and cook until browned.',
        'Step 2: Warm corn tortillas in a dry skillet.',
        'Step 3: Chop lettuce, tomatoes, and onions.',
        'Step 4: Grate cheese and prepare sour cream and salsa.',
        'Step 5: Assemble tacos with beef and toppings.',
      ],
      calories: 400,
      carbs: 25,
      fat: 20,
      protein: 30,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 28, servingId: 1, quantity: 500, name: 'Ground Beef' },
        { foodId: 29, servingId: 1, quantity: 8, name: 'Corn Tortillas' },
        { foodId: 30, servingId: 1, quantity: 1, name: 'Lettuce' },
        { foodId: 31, servingId: 1, quantity: 2, name: 'Tomatoes' },
        { foodId: 32, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 33, servingId: 1, quantity: 100, name: 'Cheddar Cheese' },
        { foodId: 34, servingId: 1, quantity: 100, name: 'Sour Cream' },
        { foodId: 35, servingId: 1, quantity: 100, name: 'Salsa' },
      ],
      tagNames: ['Mexican'],
    },
    {
      name: 'Guacamole',
      photo:
        'https://images.pexels.com/photos/5737254/pexels-photo-5737254.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 15,
      description: [
        'Step 1: Mash ripe avocados in a bowl.',
        'Step 2: Finely chop onion, tomato, and cilantro.',
        'Step 3: Mix chopped ingredients with avocados.',
        'Step 4: Add lime juice, salt, and pepper to taste.',
        'Step 5: For spicy guacamole, add chopped jalapeño.',
      ],
      calories: 250,
      carbs: 12,
      fat: 22,
      protein: 3,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 36, servingId: 1, quantity: 3, name: 'Avocados' },
        { foodId: 37, servingId: 1, quantity: 1, name: 'Lime' },
        { foodId: 38, servingId: 1, quantity: 1, name: 'Tomato' },
        { foodId: 39, servingId: 1, quantity: 1, name: 'Red Onion' },
        { foodId: 40, servingId: 1, quantity: 1, name: 'Cilantro' },
        { foodId: 41, servingId: 1, quantity: 1, name: 'Jalapeño' },
      ],
      tagNames: ['Mexican', 'Vegetarian', 'Vegan', 'Healthy', 'Gluten-Free'],
    },
    // Asian Recipes
    {
      name: 'Chicken Stir-Fry',
      photo:
        'https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 25,
      description: [
        'Step 1: Slice chicken breast into thin strips.',
        'Step 2: Chop vegetables into bite-sized pieces.',
        'Step 3: Heat oil in a wok or large skillet over high heat.',
        'Step 4: Stir-fry chicken until no longer pink.',
        'Step 5: Add vegetables and stir-fry until crisp-tender.',
        'Step 6: Add sauce and toss to coat.',
        'Step 7: Serve over rice or noodles.',
      ],
      calories: 380,
      carbs: 30,
      fat: 15,
      protein: 35,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 42, servingId: 1, quantity: 500, name: 'Chicken Breast' },
        { foodId: 43, servingId: 1, quantity: 1, name: 'Bell Pepper' },
        { foodId: 44, servingId: 1, quantity: 1, name: 'Broccoli' },
        { foodId: 45, servingId: 1, quantity: 2, name: 'Carrots' },
        { foodId: 46, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 47, servingId: 1, quantity: 3, name: 'Garlic Cloves' },
        { foodId: 48, servingId: 1, quantity: 50, name: 'Soy Sauce' },
        { foodId: 49, servingId: 1, quantity: 300, name: 'Rice' },
      ],
      tagNames: ['Asian', 'Quick Meals'],
    },
    // Indian Recipes
    {
      name: 'Butter Chicken',
      photo:
        'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 60,
      description: [
        'Step 1: Marinate chicken in yogurt and spices for at least 1 hour.',
        'Step 2: Grill or bake chicken until cooked through.',
        'Step 3: In a pan, sauté onions, garlic, and ginger.',
        'Step 4: Add tomato puree and spices, simmer for 10 minutes.',
        'Step 5: Add cream and butter, stir until combined.',
        'Step 6: Add cooked chicken and simmer for 10 minutes.',
        'Step 7: Garnish with cilantro and serve with naan or rice.',
      ],
      calories: 550,
      carbs: 20,
      fat: 35,
      protein: 40,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 59, servingId: 1, quantity: 500, name: 'Chicken Thighs' },
        { foodId: 60, servingId: 1, quantity: 100, name: 'Yogurt' },
        { foodId: 61, servingId: 1, quantity: 200, name: 'Tomato Puree' },
        { foodId: 62, servingId: 1, quantity: 100, name: 'Heavy Cream' },
        { foodId: 63, servingId: 1, quantity: 50, name: 'Butter' },
        { foodId: 64, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 65, servingId: 1, quantity: 3, name: 'Garlic Cloves' },
        { foodId: 66, servingId: 1, quantity: 20, name: 'Ginger' },
        { foodId: 67, servingId: 1, quantity: 10, name: 'Garam Masala' },
      ],
      tagNames: ['Indian'],
    },
    // Breakfast Recipes
    {
      name: 'Avocado Toast',
      photo:
        'https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 10,
      description: [
        'Step 1: Toast bread until golden and crisp.',
        'Step 2: Mash ripe avocado with a fork.',
        'Step 3: Spread avocado on toast.',
        'Step 4: Season with salt, pepper, and red pepper flakes.',
        'Step 5: Top with optional ingredients like poached egg, microgreens, or cherry tomatoes.',
      ],
      calories: 280,
      carbs: 25,
      fat: 18,
      protein: 8,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 1,
      ingredients: [
        { foodId: 76, servingId: 1, quantity: 2, name: 'Bread Slices' },
        { foodId: 77, servingId: 1, quantity: 1, name: 'Avocado' },
        { foodId: 78, servingId: 1, quantity: 1, name: 'Lemon' },
        { foodId: 79, servingId: 1, quantity: 1, name: 'Egg' },
        { foodId: 80, servingId: 1, quantity: 10, name: 'Cherry Tomatoes' },
      ],
      tagNames: ['Breakfast', 'Vegetarian', 'Healthy', 'Quick Meals'],
    },
    {
      name: 'Blueberry Pancakes',
      photo:
        'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 25,
      description: [
        'Step 1: Mix flour, baking powder, sugar, and salt in a bowl.',
        'Step 2: In another bowl, whisk together milk, eggs, and melted butter.',
        'Step 3: Combine wet and dry ingredients until just mixed.',
        'Step 4: Fold in blueberries gently.',
        'Step 5: Heat a griddle or pan and add batter to form pancakes.',
        'Step 6: Cook until bubbles form, then flip and cook other side.',
        'Step 7: Serve with maple syrup and additional blueberries.',
      ],
      calories: 420,
      carbs: 65,
      fat: 15,
      protein: 10,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 81, servingId: 1, quantity: 200, name: 'All-Purpose Flour' },
        { foodId: 82, servingId: 1, quantity: 10, name: 'Baking Powder' },
        { foodId: 83, servingId: 1, quantity: 30, name: 'Sugar' },
        { foodId: 84, servingId: 1, quantity: 250, name: 'Milk' },
        { foodId: 85, servingId: 1, quantity: 2, name: 'Eggs' },
        { foodId: 86, servingId: 1, quantity: 30, name: 'Butter' },
        { foodId: 87, servingId: 1, quantity: 150, name: 'Blueberries' },
        { foodId: 88, servingId: 1, quantity: 100, name: 'Maple Syrup' },
      ],
      tagNames: ['Breakfast', 'Vegetarian'],
    },
    // Dessert Recipes
    {
      name: 'Chocolate Chip Cookies',
      photo:
        'https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 30,
      description: [
        'Step 1: Cream together butter and sugars until light and fluffy.',
        'Step 2: Beat in eggs and vanilla extract.',
        'Step 3: In a separate bowl, combine flour, baking soda, and salt.',
        'Step 4: Gradually add dry ingredients to wet ingredients.',
        'Step 5: Fold in chocolate chips.',
        'Step 6: Drop spoonfuls of dough onto baking sheets.',
        'Step 7: Bake at 350°F for 10-12 minutes until golden brown.',
      ],
      calories: 150,
      carbs: 20,
      fat: 8,
      protein: 2,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 24,
      ingredients: [
        { foodId: 89, servingId: 1, quantity: 225, name: 'Butter' },
        { foodId: 90, servingId: 1, quantity: 150, name: 'Brown Sugar' },
        { foodId: 91, servingId: 1, quantity: 150, name: 'White Sugar' },
        { foodId: 92, servingId: 1, quantity: 2, name: 'Eggs' },
        { foodId: 93, servingId: 1, quantity: 10, name: 'Vanilla Extract' },
        { foodId: 94, servingId: 1, quantity: 280, name: 'All-Purpose Flour' },
        { foodId: 95, servingId: 1, quantity: 5, name: 'Baking Soda' },
        { foodId: 96, servingId: 1, quantity: 300, name: 'Chocolate Chips' },
      ],
      tagNames: ['Dessert', 'Baking'],
    },
    {
      name: 'Chicken Caesar Salad',
      photo:
        'https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 25,
      description: [
        'Step 1: Grill chicken breast until cooked through.',
        'Step 2: Wash and chop romaine lettuce.',
        'Step 3: Make Caesar dressing with mayonnaise, garlic, lemon juice, anchovy paste, and Parmesan.',
        'Step 4: Toss lettuce with dressing.',
        'Step 5: Slice chicken and arrange on top of salad.',
        'Step 6: Add croutons and shaved Parmesan.',
      ],
      calories: 350,
      carbs: 10,
      fat: 20,
      protein: 30,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 2,
      ingredients: [
        { foodId: 104, servingId: 1, quantity: 200, name: 'Chicken Breast' },
        { foodId: 105, servingId: 1, quantity: 1, name: 'Romaine Lettuce' },
        { foodId: 106, servingId: 1, quantity: 50, name: 'Caesar Dressing' },
        { foodId: 107, servingId: 1, quantity: 50, name: 'Croutons' },
        { foodId: 108, servingId: 1, quantity: 30, name: 'Parmesan Cheese' },
      ],
      tagNames: ['Healthy', 'Quick Meals'],
    },
    {
      name: 'Beef Stroganoff',
      photo:
        'https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 40,
      description: [
        'Step 1: Slice beef into thin strips.',
        'Step 2: Season beef with salt and pepper, then brown in a hot pan.',
        'Step 3: Remove beef and sauté onions and mushrooms in the same pan.',
        'Step 4: Add garlic and cook for 1 minute.',
        'Step 5: Return beef to pan, add beef broth and Worcestershire sauce.',
        'Step 6: Simmer for 15 minutes, then stir in sour cream.',
        'Step 7: Serve over egg noodles with chopped parsley.',
      ],
      calories: 520,
      carbs: 40,
      fat: 25,
      protein: 35,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 109, servingId: 1, quantity: 500, name: 'Beef Sirloin' },
        { foodId: 110, servingId: 1, quantity: 250, name: 'Mushrooms' },
        { foodId: 111, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 112, servingId: 1, quantity: 2, name: 'Garlic Cloves' },
        { foodId: 113, servingId: 1, quantity: 250, name: 'Beef Broth' },
        { foodId: 114, servingId: 1, quantity: 15, name: 'Worcestershire Sauce' },
        { foodId: 115, servingId: 1, quantity: 200, name: 'Sour Cream' },
        { foodId: 116, servingId: 1, quantity: 300, name: 'Egg Noodles' },
      ],
      tagNames: ['Quick Meals'],
    },
    // Adding more real recipes with real images
    {
      name: 'Greek Salad',
      photo:
        'https://images.pexels.com/photos/1211887/pexels-photo-1211887.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 15,
      description: [
        'Step 1: Chop cucumbers, tomatoes, and red onion into bite-sized pieces.',
        'Step 2: Slice bell pepper and remove seeds.',
        'Step 3: Combine vegetables in a large bowl.',
        'Step 4: Add Kalamata olives and cubed feta cheese.',
        'Step 5: In a small bowl, whisk together olive oil, red wine vinegar, oregano, salt, and pepper.',
        'Step 6: Pour dressing over salad and toss gently to combine.',
        'Step 7: Let sit for 10 minutes before serving to allow flavors to meld.',
      ],
      calories: 320,
      carbs: 15,
      fat: 25,
      protein: 8,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 124, servingId: 1, quantity: 1, name: 'Cucumber' },
        { foodId: 125, servingId: 1, quantity: 3, name: 'Tomatoes' },
        { foodId: 126, servingId: 1, quantity: 1, name: 'Red Onion' },
        { foodId: 127, servingId: 1, quantity: 1, name: 'Green Bell Pepper' },
        { foodId: 128, servingId: 1, quantity: 100, name: 'Kalamata Olives' },
        { foodId: 129, servingId: 1, quantity: 200, name: 'Feta Cheese' },
        { foodId: 130, servingId: 1, quantity: 60, name: 'Olive Oil' },
        { foodId: 131, servingId: 1, quantity: 30, name: 'Red Wine Vinegar' },
        { foodId: 132, servingId: 1, quantity: 5, name: 'Dried Oregano' },
      ],
      tagNames: ['Mediterranean', 'Greek', 'Vegetarian', 'Healthy', 'Quick Meals'],
    },
    {
      name: 'Vegetable Curry',
      photo:
        'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 45,
      description: [
        'Step 1: Heat oil in a large pot and sauté onions until translucent.',
        'Step 2: Add garlic, ginger, and curry spices, cook for 1 minute until fragrant.',
        'Step 3: Add diced vegetables and stir to coat with spices.',
        'Step 4: Pour in coconut milk and vegetable broth, bring to a simmer.',
        'Step 5: Cook until vegetables are tender, about 20 minutes.',
        'Step 6: Stir in chickpeas and spinach, cook until spinach wilts.',
        'Step 7: Season with salt and lime juice to taste.',
        'Step 8: Serve over rice with fresh cilantro.',
      ],
      calories: 380,
      carbs: 45,
      fat: 18,
      protein: 12,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 141, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 142, servingId: 1, quantity: 3, name: 'Garlic Cloves' },
        { foodId: 143, servingId: 1, quantity: 20, name: 'Ginger' },
        { foodId: 144, servingId: 1, quantity: 2, name: 'Carrots' },
        { foodId: 145, servingId: 1, quantity: 1, name: 'Bell Pepper' },
        { foodId: 146, servingId: 1, quantity: 1, name: 'Sweet Potato' },
        { foodId: 147, servingId: 1, quantity: 1, name: 'Cauliflower' },
        { foodId: 148, servingId: 1, quantity: 400, name: 'Coconut Milk' },
        { foodId: 149, servingId: 1, quantity: 250, name: 'Vegetable Broth' },
        { foodId: 150, servingId: 1, quantity: 400, name: 'Chickpeas' },
        { foodId: 151, servingId: 1, quantity: 100, name: 'Spinach' },
        { foodId: 152, servingId: 1, quantity: 1, name: 'Lime' },
        { foodId: 153, servingId: 1, quantity: 20, name: 'Curry Powder' },
      ],
      tagNames: ['Indian', 'Vegetarian', 'Vegan', 'Healthy', 'Gluten-Free'],
    },
    {
      name: 'Homemade Pizza',
      photo:
        'https://images.pexels.com/photos/905847/pexels-photo-905847.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 60,
      description: [
        'Step 1: Mix warm water, yeast, and sugar, let sit for 5 minutes until foamy.',
        'Step 2: Add flour, salt, and olive oil, knead until smooth and elastic.',
        'Step 3: Let dough rise in a warm place for 1 hour or until doubled in size.',
        'Step 4: Preheat oven to 475°F with a pizza stone if available.',
        'Step 5: Roll out dough on a floured surface to desired thickness.',
        'Step 6: Transfer to a pizza peel or baking sheet dusted with cornmeal.',
        'Step 7: Spread sauce and add toppings of your choice.',
        'Step 8: Bake for 12-15 minutes until crust is golden and cheese is bubbly.',
      ],
      calories: 300,
      carbs: 40,
      fat: 10,
      protein: 12,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 178, servingId: 1, quantity: 500, name: 'All-Purpose Flour' },
        { foodId: 179, servingId: 1, quantity: 7, name: 'Active Dry Yeast' },
        { foodId: 180, servingId: 1, quantity: 300, name: 'Warm Water' },
        { foodId: 181, servingId: 1, quantity: 30, name: 'Olive Oil' },
        { foodId: 182, servingId: 1, quantity: 5, name: 'Sugar' },
        { foodId: 183, servingId: 1, quantity: 10, name: 'Salt' },
        { foodId: 184, servingId: 1, quantity: 200, name: 'Pizza Sauce' },
        { foodId: 185, servingId: 1, quantity: 200, name: 'Mozzarella Cheese' },
        { foodId: 186, servingId: 1, quantity: 100, name: 'Toppings of Choice' },
      ],
      tagNames: ['Italian', 'Baking'],
    },
    {
      name: 'Chocolate Lava Cake',
      photo:
        'https://images.pexels.com/photos/3992131/pexels-photo-3992131.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 25,
      description: [
        'Step 1: Preheat oven to 425°F and butter four ramekins.',
        'Step 2: Melt chocolate and butter together in a double boiler.',
        'Step 3: In a separate bowl, whisk eggs, egg yolks, and sugar until pale and thick.',
        'Step 4: Fold chocolate mixture into egg mixture.',
        'Step 5: Fold in flour and salt until just combined.',
        'Step 6: Divide batter among ramekins and place on a baking sheet.',
        'Step 7: Bake for 12-14 minutes until edges are set but centers are still soft.',
        'Step 8: Let cool for 1 minute, then invert onto plates.',
        'Step 9: Serve immediately with vanilla ice cream or whipped cream.',
      ],
      calories: 400,
      carbs: 35,
      fat: 25,
      protein: 6,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 187, servingId: 1, quantity: 113, name: 'Dark Chocolate' },
        { foodId: 188, servingId: 1, quantity: 113, name: 'Butter' },
        { foodId: 189, servingId: 1, quantity: 2, name: 'Eggs' },
        { foodId: 190, servingId: 1, quantity: 2, name: 'Egg Yolks' },
        { foodId: 191, servingId: 1, quantity: 100, name: 'Sugar' },
        { foodId: 192, servingId: 1, quantity: 30, name: 'All-Purpose Flour' },
        { foodId: 193, servingId: 1, quantity: 200, name: 'Vanilla Ice Cream' },
      ],
      tagNames: ['Dessert', 'Baking'],
    },
    {
      name: 'Chicken Parmesan',
      photo:
        'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 45,
      description: [
        'Step 1: Pound chicken breasts to even thickness.',
        'Step 2: Set up breading station: flour, beaten eggs, and breadcrumbs mixed with Parmesan.',
        'Step 3: Dredge chicken in flour, dip in eggs, then coat with breadcrumb mixture.',
        'Step 4: Heat oil in a large skillet and fry chicken until golden on both sides.',
        'Step 5: Place chicken on a baking sheet, top with marinara sauce and mozzarella.',
        'Step 6: Bake at 425°F for 15-20 minutes until cheese is melted and chicken is cooked through.',
        'Step 7: Serve over spaghetti with additional marinara sauce.',
        'Step 8: Garnish with fresh basil and grated Parmesan.',
      ],
      calories: 650,
      carbs: 45,
      fat: 30,
      protein: 50,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 4,
      ingredients: [
        { foodId: 194, servingId: 1, quantity: 4, name: 'Chicken Breasts' },
        { foodId: 195, servingId: 1, quantity: 100, name: 'All-Purpose Flour' },
        { foodId: 196, servingId: 1, quantity: 3, name: 'Eggs' },
        { foodId: 197, servingId: 1, quantity: 200, name: 'Breadcrumbs' },
        { foodId: 198, servingId: 1, quantity: 100, name: 'Parmesan Cheese' },
        { foodId: 199, servingId: 1, quantity: 500, name: 'Marinara Sauce' },
        { foodId: 200, servingId: 1, quantity: 200, name: 'Mozzarella Cheese' },
        { foodId: 201, servingId: 1, quantity: 300, name: 'Spaghetti' },
        { foodId: 202, servingId: 1, quantity: 20, name: 'Fresh Basil' },
        { foodId: 203, servingId: 1, quantity: 100, name: 'Olive Oil' },
      ],
      tagNames: ['Italian'],
    },
    {
      name: 'French Onion Soup',
      photo:
        'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 70,
      description: [
        'Step 1: Thinly slice onions.',
        'Step 2: In a large pot, melt butter over medium heat.',
        'Step 3: Add onions and cook slowly, stirring occasionally, until deeply caramelized (about 40 minutes).',
        'Step 4: Add garlic and flour, cook for 1 minute.',
        'Step 5: Add wine and scrape up any browned bits from the bottom of the pot.',
        'Step 6: Add beef broth, thyme, and bay leaf, simmer for 20 minutes.',
        'Step 7: Toast baguette slices.',
        'Step 8: Ladle soup into oven-safe bowls, top with toasted bread and Gruyère cheese.',
        'Step 9: Broil until cheese is melted and bubbly.',
      ],
      calories: 320,
      carbs: 30,
      fat: 15,
      protein: 12,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 6,
      ingredients: [
        { foodId: 218, servingId: 1, quantity: 6, name: 'Onions' },
        { foodId: 219, servingId: 1, quantity: 50, name: 'Butter' },
        { foodId: 220, servingId: 1, quantity: 2, name: 'Garlic Cloves' },
        { foodId: 221, servingId: 1, quantity: 20, name: 'All-Purpose Flour' },
        { foodId: 222, servingId: 1, quantity: 120, name: 'White Wine' },
        { foodId: 223, servingId: 1, quantity: 1500, name: 'Beef Broth' },
        { foodId: 224, servingId: 1, quantity: 5, name: 'Fresh Thyme' },
        { foodId: 225, servingId: 1, quantity: 1, name: 'Bay Leaf' },
        { foodId: 226, servingId: 1, quantity: 1, name: 'Baguette' },
        { foodId: 227, servingId: 1, quantity: 200, name: 'Gruyère Cheese' },
      ],
      tagNames: ['French'],
    },
    {
      name: 'Hummus',
      photo:
        'https://images.pexels.com/photos/1618898/pexels-photo-1618898.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 15,
      description: [
        'Step 1: Drain and rinse chickpeas.',
        'Step 2: In a food processor, combine chickpeas, tahini, lemon juice, garlic, and olive oil.',
        'Step 3: Process until smooth, adding water as needed to reach desired consistency.',
        'Step 4: Season with salt, cumin, and paprika.',
        'Step 5: Transfer to a serving bowl and create a well in the center.',
        'Step 6: Drizzle with olive oil and sprinkle with paprika.',
        'Step 7: Garnish with chopped parsley.',
        'Step 8: Serve with pita bread, vegetables, or crackers.',
      ],
      calories: 180,
      carbs: 20,
      fat: 10,
      protein: 8,
      favouritesTotal: 0,
      difficulty: 'easy',
      status: 'published',
      personServing: 6,
      ingredients: [
        { foodId: 228, servingId: 1, quantity: 400, name: 'Chickpeas' },
        { foodId: 229, servingId: 1, quantity: 60, name: 'Tahini' },
        { foodId: 230, servingId: 1, quantity: 1, name: 'Lemon' },
        { foodId: 231, servingId: 1, quantity: 2, name: 'Garlic Cloves' },
        { foodId: 232, servingId: 1, quantity: 60, name: 'Olive Oil' },
        { foodId: 233, servingId: 1, quantity: 5, name: 'Cumin' },
        { foodId: 234, servingId: 1, quantity: 5, name: 'Paprika' },
        { foodId: 235, servingId: 1, quantity: 20, name: 'Fresh Parsley' },
      ],
      tagNames: ['Middle Eastern', 'Vegetarian', 'Vegan', 'Healthy', 'Quick Meals', 'Gluten-Free'],
    },
    {
      name: 'Paella',
      photo:
        'https://images.pexels.com/photos/12419160/pexels-photo-12419160.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 60,
      description: [
        'Step 1: Heat olive oil in a paella pan or large skillet.',
        'Step 2: Season chicken with salt and pepper, then brown on all sides.',
        'Step 3: Add chorizo and cook until browned.',
        'Step 4: Add onion, bell peppers, and garlic, sauté until softened.',
        'Step 5: Stir in rice, paprika, and saffron, cook for 2 minutes.',
        'Step 6: Add tomatoes and broth, bring to a simmer.',
        'Step 7: Arrange chicken, chorizo, and seafood on top of rice.',
        'Step 8: Cook without stirring until rice is tender and liquid is absorbed.',
        'Step 9: Add peas and roasted red peppers in the last 5 minutes.',
        'Step 10: Remove from heat, cover with a towel, and let rest for 5 minutes.',
        'Step 11: Garnish with lemon wedges and parsley.',
      ],
      calories: 650,
      carbs: 60,
      fat: 25,
      protein: 40,
      favouritesTotal: 0,
      difficulty: 'hard',
      status: 'published',
      personServing: 6,
      ingredients: [
        { foodId: 236, servingId: 1, quantity: 500, name: 'Chicken Thighs' },
        { foodId: 237, servingId: 1, quantity: 200, name: 'Chorizo' },
        { foodId: 238, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 239, servingId: 1, quantity: 2, name: 'Bell Peppers' },
        { foodId: 240, servingId: 1, quantity: 4, name: 'Garlic Cloves' },
        { foodId: 241, servingId: 1, quantity: 400, name: 'Short-Grain Rice' },
        { foodId: 242, servingId: 1, quantity: 10, name: 'Paprika' },
        { foodId: 243, servingId: 1, quantity: 1, name: 'Saffron' },
        { foodId: 244, servingId: 1, quantity: 400, name: 'Diced Tomatoes' },
        { foodId: 245, servingId: 1, quantity: 1000, name: 'Chicken Broth' },
        { foodId: 246, servingId: 1, quantity: 300, name: 'Mixed Seafood' },
        { foodId: 247, servingId: 1, quantity: 100, name: 'Peas' },
        { foodId: 248, servingId: 1, quantity: 100, name: 'Roasted Red Peppers' },
        { foodId: 249, servingId: 1, quantity: 1, name: 'Lemon' },
        { foodId: 250, servingId: 1, quantity: 20, name: 'Fresh Parsley' },
      ],
      tagNames: ['Spanish'],
    },
    {
      name: 'Pho',
      photo:
        'https://images.pexels.com/photos/1703272/pexels-photo-1703272.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 180,
      description: [
        'Step 1: Char onions and ginger over an open flame or under the broiler.',
        'Step 2: Toast spices in a dry pot until fragrant.',
        'Step 3: Add beef bones, charred onions and ginger, spices, and water to a large pot.',
        'Step 4: Bring to a boil, then reduce heat and simmer for 3 hours, skimming as needed.',
        'Step 5: Strain broth and return to pot, season with fish sauce and sugar.',
        'Step 6: Cook rice noodles according to package instructions.',
        'Step 7: Thinly slice raw beef.',
        'Step 8: Place noodles in bowls, top with raw beef slices.',
        'Step 9: Pour hot broth over beef to cook it.',
        'Step 10: Serve with bean sprouts, herbs, lime wedges, and hoisin sauce.',
      ],
      calories: 420,
      carbs: 50,
      fat: 10,
      protein: 35,
      favouritesTotal: 0,
      difficulty: 'hard',
      status: 'published',
      personServing: 6,
      ingredients: [
        { foodId: 275, servingId: 1, quantity: 2000, name: 'Beef Bones' },
        { foodId: 276, servingId: 1, quantity: 2, name: 'Onions' },
        { foodId: 277, servingId: 1, quantity: 100, name: 'Ginger' },
        { foodId: 278, servingId: 1, quantity: 5, name: 'Star Anise' },
        { foodId: 279, servingId: 1, quantity: 5, name: 'Cinnamon Stick' },
        { foodId: 280, servingId: 1, quantity: 5, name: 'Cloves' },
        { foodId: 281, servingId: 1, quantity: 5, name: 'Cardamom Pods' },
        { foodId: 282, servingId: 1, quantity: 5, name: 'Coriander Seeds' },
        { foodId: 283, servingId: 1, quantity: 60, name: 'Fish Sauce' },
        { foodId: 284, servingId: 1, quantity: 20, name: 'Sugar' },
        { foodId: 285, servingId: 1, quantity: 500, name: 'Rice Noodles' },
        { foodId: 286, servingId: 1, quantity: 500, name: 'Beef Sirloin' },
        { foodId: 287, servingId: 1, quantity: 200, name: 'Bean Sprouts' },
        { foodId: 288, servingId: 1, quantity: 50, name: 'Thai Basil' },
        { foodId: 289, servingId: 1, quantity: 50, name: 'Cilantro' },
        { foodId: 290, servingId: 1, quantity: 2, name: 'Limes' },
        { foodId: 291, servingId: 1, quantity: 50, name: 'Hoisin Sauce' },
      ],
      tagNames: ['Asian'],
    },
    {
      name: 'Ratatouille',
      photo:
        'https://images.pexels.com/photos/5848475/pexels-photo-5848475.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      cookingTime: 60,
      description: [
        'Step 1: Preheat oven to 375°F.',
        'Step 2: Prepare tomato sauce with olive oil, onion, garlic, and crushed tomatoes.',
        'Step 3: Spread sauce in the bottom of a baking dish.',
        'Step 4: Thinly slice eggplant, zucchini, yellow squash, and tomatoes.',
        'Step 5: Arrange vegetable slices in alternating pattern over the sauce.',
        'Step 6: Drizzle with olive oil and sprinkle with herbs, salt, and pepper.',
        'Step 7: Cover with parchment paper and bake for 45 minutes.',
        'Step 8: Uncover and bake for an additional 15 minutes until vegetables are tender.',
        'Step 9: Garnish with fresh basil before serving.',
      ],
      calories: 180,
      carbs: 20,
      fat: 10,
      protein: 5,
      favouritesTotal: 0,
      difficulty: 'medium',
      status: 'published',
      personServing: 6,
      ingredients: [
        { foodId: 292, servingId: 1, quantity: 1, name: 'Eggplant' },
        { foodId: 293, servingId: 1, quantity: 2, name: 'Zucchini' },
        { foodId: 294, servingId: 1, quantity: 2, name: 'Yellow Squash' },
        { foodId: 295, servingId: 1, quantity: 4, name: 'Tomatoes' },
        { foodId: 296, servingId: 1, quantity: 1, name: 'Onion' },
        { foodId: 297, servingId: 1, quantity: 3, name: 'Garlic Cloves' },
        { foodId: 298, servingId: 1, quantity: 400, name: 'Crushed Tomatoes' },
        { foodId: 299, servingId: 1, quantity: 60, name: 'Olive Oil' },
        { foodId: 300, servingId: 1, quantity: 5, name: 'Herbes de Provence' },
        { foodId: 301, servingId: 1, quantity: 20, name: 'Fresh Basil' },
      ],
      tagNames: ['French', 'Vegetarian', 'Vegan', 'Healthy', 'Gluten-Free'],
    },
  ]

  // Create all recipes in the database
  for (const recipe of recipes) {
    const recipeTagConnections = recipe.tagNames.map((tagName) => ({
      tag: { connect: { id: tags[tagName].id } },
    }))

    await prisma.recipe.create({
      data: {
        name: recipe.name,
        photo: recipe.photo,
        cookingTime: recipe.cookingTime,
        description: recipe.description,
        calories: recipe.calories,
        carbs: recipe.carbs,
        fat: recipe.fat,
        protein: recipe.protein,
        favouritesTotal: recipe.favouritesTotal,
        difficulty: recipe.difficulty,
        status: recipe.status,
        personServing: recipe.personServing,
        userId: userId,
        ingredients: {
          create: recipe.ingredients,
        },
        tags: {
          create: recipeTagConnections,
        },
      },
    })
  }
}

// main()
//   .catch((error) => {
//     console.error(error)
//     process.exit(1)
//   })
//   .finally(async () => {
//     await prisma.$disconnect()
//   })
