import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import Providers from '@/components/common/Providers'
import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer'
import './globals.css'
import { getUserInfoWithoutRedirect } from '@/actions/auth/getUserInfoWithoutRedirect'

const robotoSans = Roboto({
  weight: ['400', '500', '700'],
  variable: '--font-roboto-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await getUserInfoWithoutRedirect()

  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={`${robotoSans.variable} flex h-full flex-col pt-15 antialiased md:pt-20`}>
        <Providers>
          <Header user={user} />
          {children}
          <Footer />
        </Providers>
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  )
}
