import type { Metadata } from 'next'
import { Cantarell, Roboto } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import Providers from '@/components/common/Providers'
import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer'
import './globals.css'

const cantarellSans = Cantarell({
  weight: ['400', '700'],
  variable: '--font-cantarell-sans',
  subsets: ['latin'],
})

const robotoSans = Roboto({
  weight: ['400', '500', '700'],
  variable: '--font-roboto-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={`${cantarellSans.variable} ${robotoSans.variable} flex h-full flex-col pt-15 antialiased md:pt-20`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  )
}
