import type { Metadata } from 'next'
import { Cantarell, Roboto } from 'next/font/google'
import './globals.css'

const cantarellSans = Cantarell({
  weight: ['400', '700'],
  variable: '--font-cantarell-sans',
  subsets: ['latin'],
})

const robotoSans = Roboto({
  weight: ['400', '700'],
  variable: '--font-roboto-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${cantarellSans.variable} ${robotoSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
